# NLP Project - Git Test

### Perceptron - Single Unit Neural Network
Here I am simply going to try to construct from scratch and mostly from memory a perceptron using the tools given by PyTorch.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.__version__

'1.4.0'

In [2]:
class Perceptron(nn.Module):
    
    # What is the __init__ method? It is necessary for all classes in python. It initializes an object of the class type.
    # It is used to initialize an object of the type you are defining.
    def __init__(self,input_dim):
        super(Perceptron, self).__init()
        self.fc1 = nn.Linear(input_dim, 1)
    
    # What is the forward method? The forward method defines a forward pass.
    def forward():
        

SyntaxError: unexpected EOF while parsing (<ipython-input-2-abc1a8a5df15>, line 11)

In [3]:
a = [1,2,3,4,100,12,44]
enumerate(a)

In [4]:
[i for i in enumerate(a)]

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 100), (5, 12), (6, 44)]

In [5]:
sentence = "He who fights with monsters might take care lest he thereby become a monster. And if you gaze for long into an abyss, the abyss gazes also into you."
sentence = sentence.lower()
words = sentence.split(' ')
words

['he',
 'who',
 'fights',
 'with',
 'monsters',
 'might',
 'take',
 'care',
 'lest',
 'he',
 'thereby',
 'become',
 'a',
 'monster.',
 'and',
 'if',
 'you',
 'gaze',
 'for',
 'long',
 'into',
 'an',
 'abyss,',
 'the',
 'abyss',
 'gazes',
 'also',
 'into',
 'you.']

In [6]:
import string
for i in range(len(words)):
    words[i] = words[i].strip(string.punctuation)
words

['he',
 'who',
 'fights',
 'with',
 'monsters',
 'might',
 'take',
 'care',
 'lest',
 'he',
 'thereby',
 'become',
 'a',
 'monster',
 'and',
 'if',
 'you',
 'gaze',
 'for',
 'long',
 'into',
 'an',
 'abyss',
 'the',
 'abyss',
 'gazes',
 'also',
 'into',
 'you']

In [7]:
vocab = list(set(words))
vocab

['fights',
 'you',
 'lest',
 'thereby',
 'for',
 'who',
 'an',
 'he',
 'gaze',
 'gazes',
 'abyss',
 'might',
 'monster',
 'also',
 'become',
 'long',
 'into',
 'monsters',
 'a',
 'the',
 'take',
 'with',
 'and',
 'if',
 'care']

In [8]:
vocab_size = len(vocab)
vocab_size

25

In [9]:
word_to_index = {word: index for index, word in enumerate(vocab)}
word_to_index

{'fights': 0,
 'you': 1,
 'lest': 2,
 'thereby': 3,
 'for': 4,
 'who': 5,
 'an': 6,
 'he': 7,
 'gaze': 8,
 'gazes': 9,
 'abyss': 10,
 'might': 11,
 'monster': 12,
 'also': 13,
 'become': 14,
 'long': 15,
 'into': 16,
 'monsters': 17,
 'a': 18,
 'the': 19,
 'take': 20,
 'with': 21,
 'and': 22,
 'if': 23,
 'care': 24}

In [10]:
# Let's create a one-hot encoding.
import numpy as np
import torch
one_hot_encoding = []
for word in vocab:
    temp = np.zeros(vocab_size)
    temp[word_to_index[word]] = 1
    one_hot_encoding.append([int(i) for i in temp.tolist()])
one_hot_encoding = torch.tensor(one_hot_encoding)
one_hot_encoding

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 

In [11]:
from torch.nn.functional import one_hot

word_indexes = torch.tensor([word_to_index[word] for word in vocab], dtype=torch.long)

one_hot_encoding2 = one_hot(word_indexes)

one_hot_encoding == one_hot_encoding2

tensor([[True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, Tr

In [12]:
# HYPERPARAMETERS
CONTEXT_SIZE = 2

EMBEDDING_DIM = 10

HIDDEN_DIM = 256

In [13]:
# BUILDING TRIGRAMS
trigrams = [([words[i-2], words[i-1]], words[i]) for i in range(2, len(words))]
trigrams

[(['he', 'who'], 'fights'),
 (['who', 'fights'], 'with'),
 (['fights', 'with'], 'monsters'),
 (['with', 'monsters'], 'might'),
 (['monsters', 'might'], 'take'),
 (['might', 'take'], 'care'),
 (['take', 'care'], 'lest'),
 (['care', 'lest'], 'he'),
 (['lest', 'he'], 'thereby'),
 (['he', 'thereby'], 'become'),
 (['thereby', 'become'], 'a'),
 (['become', 'a'], 'monster'),
 (['a', 'monster'], 'and'),
 (['monster', 'and'], 'if'),
 (['and', 'if'], 'you'),
 (['if', 'you'], 'gaze'),
 (['you', 'gaze'], 'for'),
 (['gaze', 'for'], 'long'),
 (['for', 'long'], 'into'),
 (['long', 'into'], 'an'),
 (['into', 'an'], 'abyss'),
 (['an', 'abyss'], 'the'),
 (['abyss', 'the'], 'abyss'),
 (['the', 'abyss'], 'gazes'),
 (['abyss', 'gazes'], 'also'),
 (['gazes', 'also'], 'into'),
 (['also', 'into'], 'you')]

In [14]:
import torch.nn as nn
embedding = nn.Embedding(vocab_size, EMBEDDING_DIM)
embedding(torch.tensor([i for i in range(vocab_size)])).view((vocab_size, EMBEDDING_DIM))

tensor([[ 1.6006, -0.6645,  0.5432,  0.4950, -1.0713,  0.2783, -1.7713, -0.4044,
         -1.1901,  0.1015],
        [ 0.4279, -1.0237, -0.8317,  0.0199,  1.5384, -0.3903,  0.6419,  0.2319,
         -1.9515,  1.4657],
        [-0.0294,  0.6504,  0.2849, -1.5047,  0.2431, -2.3651, -0.3938, -0.4906,
          1.1304,  0.0687],
        [ 0.3079,  0.2865,  0.7343, -0.6467, -0.9201,  2.0393,  1.9687, -0.6132,
         -0.7404, -0.3695],
        [-0.7188, -0.0891, -0.1131, -1.6059, -0.2689,  1.2588, -0.9100,  0.0600,
         -0.4551,  0.1986],
        [ 1.0518,  0.8081,  1.2864, -0.0554,  1.5136,  2.1389, -0.0725, -0.2635,
         -0.1292,  0.8605],
        [ 1.1409,  1.5963, -0.4233, -0.2144, -0.0989, -0.4040,  0.7161,  0.3316,
         -0.3653, -0.0722],
        [ 1.5758,  0.4012, -0.0488,  0.7433, -0.2327, -0.5334, -1.5111, -0.3532,
          0.3004,  0.8640],
        [-0.4029, -1.2956,  1.7387,  1.2478,  0.4211,  0.4790,  0.9029,  0.5276,
         -2.0833,  1.4020],
        [ 0.1821, -

In [15]:
torch.ones(5,7,8).stride()
# To jump from the i_th dim_1 to the j_th dim_1 holding all else equal takes |j-i|*56 moves.
# To jump from the i_th dim_2 to the j_th dim_2 holding all else equal takes |j-i|*8 moves.
# To jump from the i_th dim_3 to the j_th dim_3 holding all else equal takes |j-i| moves.

(56, 8, 1)

In [16]:
# Embeddings are modified modules.
nn.Embedding.__bases__

(torch.nn.modules.module.Module,)

In [17]:
# This is the fundamental PyTorch class on which all models are built.
nn.Module.__bases__

(object,)

In [18]:
# Let's explore the following NGram Language Modeler...
import torch.nn as nn
import torch.nn.functional as F

class NGramLanguageModeler(nn.Module):
    
    def __init__(self, vocab_size, embedding_dim, context_size):
        # This use of super makes Python start looking for an __init__ method associated with a dummy object
        # instantiation (self) one level above NGramLanguageModel (in this case Module).
        super(NGramLanguageModeler, self).__init__() # Does the simple Module initialization.
        self.embeddings = nn.Embedding(vocab_size, embedding_dim) # This module now contains a sub-module of class Embeddings.
        self.linear1 = nn.Linear(context_size * embedding_dim, HIDDEN_DIM) # Again linear is a simple affine transformation.
        self.linear2 = nn.Linear(HIDDEN_DIM, vocab_size)
        
    def forward(self, inputs): # Takes a temporary object of this class (to access data and methods) and also takes input vector
        # The forward pass.
        # We have a model structure, composed essentially of a collection of matrix multiplications
        # and other similar computations which keep track of their source so that gradients can be computed.
        # With the forward pass, we simply run our computations in order.
        embeds = self.embeddings(inputs).view(1,-1) # We need to essentially concatenate these two vectors
        out = F.relu(self.linear1(embeds)) 
        out = self.linear2(out)
        log_probs = F.log_softmax(out, -1) # gives us a log probability over the vocabulary
        return log_probs
        

So basically above we have our model. But it is trash. It doesn't give good results because all of the weights and biases and embeddings are totally random. We need to hone it by giving it some feedback so that it adjusts itself. We do this by running it on some data and computing the loss with respect to some target output, and then backpropagating. We do this for several epochs.

In [19]:
import torch.optim as optim

learning_rate = 0.001
losses = []
loss_function = nn.NLLLoss() # negative log likelihood
model = NGramLanguageModeler(len(vocab), EMBEDDING_DIM, CONTEXT_SIZE)
optimizer = optim.SGD(model.parameters(), lr = learning_rate)

In [20]:
model.parameters

<bound method Module.parameters of NGramLanguageModeler(
  (embeddings): Embedding(25, 10)
  (linear1): Linear(in_features=20, out_features=256, bias=True)
  (linear2): Linear(in_features=256, out_features=25, bias=True)
)>

In [21]:
# Let's briefly inspect the model parameters
# We can use the iterator model.parameters() to get the tensors which constitute our models parameters.
# In this case, the output reveals that the first parameter is a matrix with 25 rows and ten columns.
# That is our embedding table of 25 words each with a vector representation of length 10.
# Our next paramater is a matrix with 256 rows and 20 columns. This represents weights of the connections between
# our two stacked word embeddings (from the conditioned word pair) and our 256 hidden units.
# The next is a vector of length 256. These are the biases of our 256 hidden units.
# Then we have a matrix with 25 rows and 256 columns. These are the weights from the 256 hidden units
# to the 25 possible output words.
for param in model.parameters():
    print(param.shape)

torch.Size([25, 10])
torch.Size([256, 20])
torch.Size([256])
torch.Size([25, 256])
torch.Size([25])


In [22]:
# Now let's train our model.
from tqdm import tqdm # A really great progress bar library

for epoch in range(25):
    total_loss = 0 # Initialize loss to 0
    
    iterator = tqdm(trigrams)
    # tqdm wraps an iterable and returns progress by showing how many iterations you've gone through
    # and how many left you have to go. tqdm(iterable) can be treated like an iterator.
    
    for context, target in iterator:
        # For each context, for each of the two words in the context, replace it with its index.
        context_ids = torch.tensor([word_to_index[w] for w in context], dtype=torch.long)
        
        # Zero out gradients since gradients are accumulated in PyTorch.
        model.zero_grad()
        
        log_probs = model(context_ids)
        
        # previously defined as negative log likelihood loss
        loss = loss_function(log_probs, torch.tensor([word_to_index[target]], dtype=torch.long))
        
        # This computes the gradient of the loss with respect to ALL THE PARAMETERS
        # through the efficient dynamic programming algorithm known as backpropagation
        loss.backward()
        
        # Here the optimizer takes one step (with size of learning rate) in the direction of the gradient.
        # In other words it updates all parameters (considered as a vector) by some scaled version of the 
        # gradient vector.
        optimizer.step()
        
        # loss.item() gets the loss as a float
        total_loss += loss.item()
        
        # Simply adds the loss to our progress output
        iterator.set_postfix(loss=float(loss))
        
    # Simply keeps track of the loss at each epoch.    
    losses.append(total_loss)

100%|██████████| 27/27 [00:00<00:00, 436.67it/s, loss=2.13]


In [27]:
# Certain types of layers or modules behave differently during training (updating weights)
# and evaluation/testing (actually pushing values through the network).
# It is good practice to specify when your model is in training with model.train()
# and when it is in evaluation mode with model.eval().
model.eval()

# Note that this returns a model with the previously specified structure

NGramLanguageModeler(
  (embeddings): Embedding(25, 10)
  (linear1): Linear(in_features=20, out_features=256, bias=True)
  (linear2): Linear(in_features=256, out_features=25, bias=True)
)

In [31]:
import numpy as np

# This simply runs our model without its associated gradient data, since this is unnecessary outside of training.
with torch.no_grad():
    context = ["monster", "and"]
    context_indices = torch.tensor([word_to_index[w] for w in context], dtype=torch.long)
    pred = model(context_indices)
    print(pred)
    index_of_prediction = np.argmax(pred)
    print(vocab[index_of_prediction])

tensor([[-3.2772, -2.7866, -3.3541, -3.2785, -3.2696, -3.4185, -3.3924, -2.9264,
         -3.4512, -3.4004, -2.9080, -3.2412, -2.9587, -3.3246, -3.3224, -3.2233,
         -3.1292, -3.1498, -3.3067, -3.2114, -2.9347, -3.7021, -3.4993, -3.0356,
         -3.5812]])
you


# Exploring RNNs in PyTorch